# SysWatch configuration
export EMAIL_ADMIN="admin@devarea.htb"

export CPU_THRESHOLD=80
export MEM_THRESHOLD=80
export DISK_THRESHOLD=80
export NET_MAX_CONNECTIONS=500
export NET_MAX_PER_IP=50

export SERVICES=("apache2:1" "ssh:0" "syswatch-web:0" "vsftpd:0" "hoverfly:0" "syswatch-monitor:0")

export LOG_DIR="/opt/syswatch/logs"
export CPU_MEM_LOG="$LOG_DIR/cpu-mem.log"
export DISK_LOG="$LOG_DIR/disk.log"
export NETWORK_LOG="$LOG_DIR/network.log"
export LOG_MONITOR_LOG="$LOG_DIR/log-alerts.log"
export SERVICE_LOG="$LOG_DIR/service.log"

export PLUGIN_DIR="/opt/syswatch/plugins"
export SYSWATCH_USER="syswatch"

