[libdefaults]
rdns = false
dns_lookup_kdc = false
default_realm = CHECKPOINT.HTB
forwardable = true
ccache_type = FILE

[realms]
CHECKPOINT.HTB = {
    kdc = 10.129.41.25
    admin_server = 10.129.41.25
    default_domain = checkpoint.htb
}

[domain_realm]
.checkpoint.htb = CHECKPOINT.HTB
checkpoint.htb = CHECKPOINT.HTB
