[libdefaults]
	default_realm = LOGGING.HTB
	dns_lookup_kdc = false

[realms]
	LOGGING.HTB = {
		kdc = dc01.logging.htb
		admin_server = dc01.logging.htb
	}

[domain_realm]
	.logging.htb = LOGGING.HTB
	logging.htb = LOGGING.HTB
